const players = {
  tercero: {
    top: {
      likely: ['camille', 'aatrox', 'jax', 'poppy', 'ornn'],
      possible: [
        'gwen',
        'fiora',
        'irelia',
        'mordekaiser',
        'rumble',
        'renekton',
        'riven',
        'swain',
        'zac',
        'jayce',
      ],
      neutral: [
        "cho'gath",
        'gnar',
        'pantheon',
        'olaf',
        'quinn',
        'twisted fate',
        'yone',
        'sylas',
        'kayn',
      ],
      unlikely: [
        'aurora',
        'galio',
        'garen',
        'maokai',
        'malphite',
        'shen',
        'sion',
        'trundle',
        'warwick',
        'kayle',
        'gragas',
        'gangplank',
        'kasante',
        'rammus',
        'volibear',
      ],
      impossible: [
        'akshan',
        'ambessa',
        'briar',
        'darius',
        'Dr. mundo',
        'tryndamere',
        'illaoi',
        'nasus',
        'sett',
        'nafiri',
        'teemo',
        'wukong',
        'yasuo',
        'yorik',
        'urgot',
        'vayne',
        'varus',
        'tahm kench',
      ],
    },
    support: {
      likely: [
        'lulu',
        'janna',
        'camille',
        'pantheon',
        'elise',
        'poppy',
        'thresh',
        'rell',
        'leona',
        'rakan',
        'karma',
        'alistar',
        'nautilus',
        'nami',
        'taliyah',
        'maokai',
        'pyke',
        'senna',
        'swain',
      ],
    },
    jungle: {
      likely: ['jarvan IV', 'kayn', 'diana', 'ivern', 'graves', 'viego', 'gwen', 'zac'],
    },
    adc: {
      likely: [
        'taliyah',
        'swain',
        'ashe',
        'caitlyn',
        'draven',
        'jinx',
        "kai'sa",
        'tristana',
        'jhin',
        'miss fortune',
        'nilah',
        'samira',
        'xayah',
        'zeri',
        'sivir',
        'corki',
      ],
    },
  },
  benju: {
    jungle: {
      likely: ['diana', 'nunu', 'kindred', 'jarvan IV', 'ivern', 'lillia', 'vi', 'skarner'],
      possible: [
        'ekko',
        'kayn',
        "kha'zix",
        'wukong',
        'warwick',
        'pantheon',
        'xin zhao',
        'hecarim',
        'sejuani',
      ],
      neutral: ['poppy', 'maokai', 'talon', "bel'veth", 'graves', 'brand'],
      unlikely: ['teemo', 'volibear', 'Master yi', 'amumu', 'fiddlesticks', 'nocturne', 'karthus'],
      impossible: ['gragas', 'lee sin', 'rengar', 'shaco', 'jax', 'briar'],
    },
    support: {
      likely: ['bardo', 'nautilus', 'rakan', 'maokai', 'leona'],
      possible: ['blitzcrank', 'milio', 'tahm kench'],
      neutral: ['pantheon', 'poppy', 'karma'],
      unlikely: ['morgana', 'lux', 'nami', 'janna', 'lulu'],
      impossible: ['alistar', 'thresh', 'elise'],
    },
  },
  eze: {
    jungle: {
      likely: ['amumu', 'briar', 'nocturne', 'fiddlesticks', 'trundle', 'warwick'],
      possible: ['jax', "bel'veth", 'vi', 'kayn', 'Master yi', 'rammus', 'sejuani', 'jarvan IV'],
      neutral: [
        'viego',
        'lillia',
        'wukong',
        'ekko',
        'volibear',
        'zac',
        'sylas',
        'mordekaiser',
        'teemo',
        'skarner',
      ],
      unlikely: [
        'pantheon',
        'hecarim',
        'gragas',
        'zed',
        'sett',
        'shyvana',
        'rumble',
        'shaco',
        "kha'zix",
        'diana',
        'Dr. mundo',
        'xin zhao',
        'poppy',
      ],
      impossible: [
        'elise',
        'maokai',
        'udyr',
        'graves',
        'gwen',
        'yorik',
        'ivern',
        'kindred',
        'rengar',
        'neeko',
        'nidalee',
        'karthus',
        'morgana',
        'twitch',
        "rek'sai",
      ],
    },
    top: {
      likely: ['shen', 'trunle', 'Dr. mundo', 'jax', 'garen', 'warwick', 'volibear'],
      possible: [
        'olaf',
        'maokai',
        'tahm kench',
        'malphite',
        'sett',
        'gragas',
        'teemo',
        'illaoi',
        'sylas',
        'rumble',
        'zac',
        'wukong',
        'mordekaiser',
      ],
      neutral: ['ornn', 'pantheon', "cho'gath", 'gnar', 'nasus', 'darius', 'poppy'],
      unlikely: ['urgot', 'yorick', 'irelia', 'xin zhao', 'gwen', 'camille', 'sion', 'tryndamere'],
      impossible: [
        'renekton',
        'kled',
        'ambessa',
        'kennen',
        'vladimir',
        'signed',
        "k'sante",
        'aatrox',
        'gangplank',
        'heimerdinger',
        'fiora',
        'riven',
        'kayle',
        'swain',
        'graves',
        'yasuo',
        'yone',
        'quinn',
      ],
    },
  },
  sagi: {
    support: {
      likely: [
        'nami',
        'rell',
        'lulu',
        'seraphine',
        'janna',
        'rakan',
        'sona',
        'soraka',
        'leona',
        'yummi',
      ],
      possible: [
        'morgana',
        'karma',
        'renata glasc',
        'sena',
        'maokai',
        'swain',
        'braum',
        'nautilus',
        'alistar',
        'lux',
        'taric',
      ],
      neutral: ['neeko', 'pyke', 'zyra', 'pantheon', "vel'koz"],
      unlikely: ['bardo', 'milio', 'brand', 'thresh', 'xerath', 'tahm kench'],
      impossible: ['elise', 'blitzcrank', 'poppy', 'zilean'],
    },
    mid: {
      likely: ['ahri', 'anivia', 'malzahar', 'ryze', 'cassiopeia'],
      possible: [
        'lissandra',
        'akali',
        'vex',
        'orianna',
        'zoe',
        'ekko',
        'irelia',
        'lux',
        'nafiri',
        'veigar',
        'annie',
        'syndra',
        'xerath',
        'aurelion sol',
        'galio',
        'ziggs',
        'mel',
      ],
      neutral: ['akshan', 'sylas', 'qiyana', 'hwei', 'talon', 'azir', 'aurora'],
      unlikely: [
        'kassadin',
        'viktor',
        'yone',
        'yasuo',
        'taliyah',
        'diana',
        'twisted fate',
        'vladimir',
      ],
      impossible: ['katarina', 'leblanc', 'fizz', 'zed'],
    },
    top: {
      likely: ["cho'gath", 'kayle', 'maokai', 'poppy', 'riven', 'quinn', 'urgot', 'ryze'],
      possible: [
        'aatrox',
        'fiora',
        'garen',
        'ornn',
        'sett',
        'mordekaiser',
        'irelia',
        'gnar',
        "k'sante",
        'malphite',
        'pantheon',
        'sion',
        'shen',
        'volibear',
        'rumble',
        'renekton',
      ],
      neutral: [
        'camille',
        'darius',
        'gangplank',
        'gwen',
        'illaoi',
        'jayce',
        'kennen',
        'ambessa',
        'vladimir',
      ],
      unlikely: ['Dr. mundo', 'kled', 'nasus', 'yone', 'tryndamere'],
      impossible: ['jax', 'teemo', 'singed', 'yorki', 'trunle', 'gragas'],
    },
  },
  marco: {
    mid: {
      likely: [
        'ahri',
        'corki',
        'anivia',
        'lissandra',
        'viktor',
        'vladimir',
        'orianna',
        'galio',
        'azir',
        'vex',
        'ryze',
        'annie',
        'malzhar',
        'pantheon',
        'leblanc',
        'syndra',
        'kassadin',
        'kayle',
      ],
      possible: [
        'yone',
        'veigar',
        'zed',
        "vel'koz",
        'brand',
        'ekko',
        'malphite',
        'lux',
        'rumble',
        'nekko',
        'taliyah',
        'swain',
        'sylas',
        'ziggs',
        'xerath',
        'aurora',
        "kog'maw",
        'sion',
        'varus',
        'caitlyn',
        'jayce',
        'qiyana',
      ],
      neutral: [
        "cho'gath",
        'fizz',
        'gragas',
        'heimerdinger',
        'kennen',
        'lucian',
        'lulu',
        'diana',
        'irelia',
        'gangplank',
        'renekton',
        'yasuo',
        'seraphine',
        'karma',
        'talon',
        'twisted fate',
        'zoe',
        'hwei',
        'aatrox',
        'aurelion sol',
        'riven',
      ],
      unlikely: [],
      impossible: ['katarina', 'akali'],
    },
    jungle: {
      likely: ['amumu', 'gragas', 'jarvan IV', 'lee sin', 'kayn', 'vi', 'rammus'],
      possible: [
        'lillia',
        "rek'sai",
        'nocturne',
        'shyvana',
        'trundle',
        'warwick',
        'zac',
        'Master yi',
        'diana',
      ],
      neutral: [
        'hecarim',
        'evelynn',
        'graves',
        'elise',
        'ivern',
        'kindred',
        "kha'zix",
        'poppy',
        'olaf',
        'sejuani',
        'wukong',
        'volibear',
        'twitch',
        'xin zhao',
        'viego',
        "bel'veth",
        'maokai',
        "cho'gath",
        'pantheon',
        'talon',
      ],
      unlikely: [
        'fiddlesticks',
        'taliyah',
        'ekko',
        'sion',
        'rumble',
        'nidalee',
        'nunu',
        'rengar',
        'shaco',
        'udyr',
        'briar',
        'skarner',
        'yorick',
        'gwen',
        'zyra',
        'jax',
        'zed',
        'teemo',
      ],
      impossible: [],
    },
  },
  marc: {
    support: {
      likely: ['rell', 'leona', 'karma', 'seraphine', 'lulu'],
      possible: [
        'amumu',
        'braum',
        'mao kai',
        'renata glasc',
        'zyra',
        'neeko',
        'thresh',
        'janna',
        'blitzcrank',
        'senna',
        'poppy',
        'nami',
        'soraka',
        'yummi',
        'lux',
      ],
      neutral: [
        'ashe',
        'elise',
        'galio',
        'rakan',
        'milio',
        'pantheon',
        'alistar',
        'zilean',
        'swain',
        'tahm kench',
        'taric',
        'brand',
        'xerath',
      ],
      unlikely: ['bardo', 'pyke'],
      impossible: ['morgana', 'sona'],
    },
    mid: {
      likely: [
        'galio',
        'lissandra',
        'neeko',
        'orianna',
        'lucian',
        'varus',
        "cho'gath",
        'seraphine',
      ],
      possible: ['cassiopeia', 'syndra', 'ziggs'],
      neutral: [
        'azir',
        'ahri',
        'akali',
        'hwei',
        'aurora',
        'vex',
        'yone',
        'leblanc',
        'viktor',
        'sylas',
        'corki',
        'taliyah',
        'smloder',
        'anivia',
      ],
      unlikely: [],
      impossible: [],
    },
    jungle: {
      likely: ['amumu', 'mao kai', 'nocturne', 'vi', 'wukong', 'lillia'],
      possible: ['jarvan IV', 'diana'],
      neutral: [
        'evelynn',
        'sejuani',
        'viego',
        'volibear',
        'skarner',
        'xin zhao',
        'kayn',
        'briar',
        'zyra',
        'zac',
        'hecarim',
        "kha'zix",
      ],
      unlikely: [],
      impossible: [],
    },
    top: {
      likely: ['ornn', 'poppy', 'malphite'],
      possible: ['gnar', 'sion', 'trundle', 'renekton', "cho'gath", 'maokai'],
      neutral: [
        'aatrox',
        'camile',
        'gragas',
        'gwen',
        'fiora',
        'gnakplank',
        'darius',
        "k'sante",
        'ambessa',
        'olaf',
        'jax',
        'rumble',
        'shen',
        'kayle',
        'jayce',
      ],
      unlikely: [],
      impossible: [],
    },
  },
  miki: {
    adc: {
      likely: [
        'brand',
        'caitlyn',
        'kalista',
        'corki',
        "kai'sa",
        'draven',
        'jinx',
        "kog'maw",
        'lucian',
        'nilah',
        'miss fortune',
        'xayah',
        'senna',
        'syndra',
        'veigar',
        'vayne',
        'viktor',
        'smolder',
      ],
      possible: [
        'aphelios',
        'ashe',
        'seraphine',
        'sivir',
        'zeri',
        'ziggs',
        'varus',
        'ziggs',
        'varus',
        'tristana',
        'yasuo',
        'yone',
        'twitch',
        'samira',
      ],
      neutral: ['karthus', 'cassiopeia', 'lee sin', 'swain'],
      unlikely: ["cho'gath", 'jhin', 'mordekaiser'],
      impossible: [],
    },
    support: {
      likely: [
        'alistar',
        'thresh',
        'amumu',
        'annie',
        'brand',
        'blitzcrank',
        'janna',
        'leblanc',
        'lulu',
        'nami',
        'nautilus',
        'morgana',
        'rakan',
        'sylas',
        'senna',
        'seraphine',
        'veigar',
        'soraka',
        'ziggs',
      ],
      possible: [
        'braum',
        'renata glasc',
        'poppy',
        'swain',
        'miss fortune',
        'karma',
        'galio',
        'rell',
        'milio',
        'neeko',
        'pyke',
        'sona',
        'tahm kench',
        'zac',
        'zilean',
      ],
      neutral: ['elise', 'ivern', 'pantheon', 'mao kai', 'sion', 'hwei', 'shen'],
      unlikely: ['ashe', 'lux', 'yummi'],
      impossible: ['shaco'],
    },
    mid: {
      likely: [
        'ahri',
        'anivia',
        'annie',
        'brand',
        'corki',
        'fizz',
        'karma',
        'kayle',
        'leblanc',
        'lucian',
        'ezreal',
        "kog'maw",
        'malzhar',
        'malphite',
        'morgana',
        'orianna',
        'seraphine',
        'nautilus',
        'veigar',
        'viktor',
        'smolder',
        'tristana',
        'syndra',
        'ziggs',
        'zilean',
        'varus',
      ],
      possible: [
        'akali',
        'azir',
        'cassiopeia',
        'diana',
        'ekko',
        'galio',
        'jayce',
        'kassadin',
        'katarina',
        'lissandra',
        'neeko',
        'lulu',
        'xerath',
        'sylas',
        'twisted fate',
        'yone',
        'yasuo',
        'zed',
        'vex',
        'hwei',
        'zyra',
        'mel',
      ],
      neutral: [
        'akshan',
        'aurelion',
        'irelia',
        'gangplank',
        'gragas',
        'karthus',
        'kennen',
        'nafiri',
        'pantheon',
        'qiyana',
        'renekton',
        'riven',
        'quinn',
        'rumble',
        'swain',
        'taliyah',
        'talon',
        "vel'koz",
        'aurora',
        'zoe',
      ],
      unlikely: ['lulu', 'mordekaiser'],
      impossible: ['heimerdinger'],
    },
  },
};
